global:
  name: train-matrn
  phase: train
  stage: train-super
  workdir: results
  seed: ~
 
dataset:
  train: {
    roots: ['train'],
    batch_size: 12 ##384
  }
  test: {
    roots: ['validation'],
    batch_size: 12 ##384
  }
  valid: {
    roots: ['validation'],
    batch_size: 12 ##384
  }
  data_aug: True
  multiscales: False
  num_workers: 0

training:
  epochs: 10
  show_iters: 50
  eval_iters: 3000
  save_iters: 3000

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  args: {
    betas: !!python/tuple [0.9, 0.999], # for default Adam 
  }
  scheduler: {
    periods: [6, 4],
    gamma: 0.1,
  }

model:
  name: 'modules.model_matrn_iter.MATRN'
  iter_size: 3
  ensemble: ''
  use_vision: False
  vision: {
    checkpoint: 'pretrain/pretrain-vision-model/best-pretrain-vision-model.pth',
    loss_weight: 1.,
    attention: 'position',
    backbone: 'transformer',
    backbone_ln: 3,
  }
  language: {
    checkpoint:  'pretrain/pretrain-language-model/pretrain-language-model.pth',
    num_layers: 4,
    loss_weight: 1.,
    detach: True,
    use_self_attn: False
  }
  alignment: {
    checkpoint: ~,
    num_layers: 2,
    loss_weight: 1.,
    use_self_attn: False,
  }
